/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Vagros_allowlist__factory } from "./Vagros_allowlist__factory";
export { Vagros_cycle_token__factory } from "./Vagros_cycle_token__factory";
export { Vagros_fakeUSDT__factory } from "./Vagros_fakeUSDT__factory";
export { Vagros_marketplace__factory } from "./Vagros_marketplace__factory";
